# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 03:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('middle_initial', models.CharField(blank=True, default='', max_length=1, verbose_name='MI')),
                ('supervisor', models.CharField(blank=True, default='supervisor', max_length=40)),
                ('division', models.CharField(choices=[('MLHC', 'MLHC'), ('NCS', 'NCS'), ('MTE', 'MTE'), ('NIT', 'NIT'), ('WTE', 'WTE'), ('PRC', 'PRC'), ('PTI', 'PTI'), ('NCSA', 'NCSA'), ('NCSAR', 'NCSAR'), ('NCSMD', 'NCSMD'), ('WLTIC', 'WLTIC')], default='NIT', max_length=5)),
                ('office', models.CharField(choices=[('2301', '2301'), ('2302', '2302'), ('2303', '2303'), ('4999', '4999')], default='2301', max_length=4)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('job_title', models.CharField(choices=[('EO', 'Escrow Officer'), ('TO', 'Title Officer')], default='EO', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('group_email', models.EmailField(default='group@example.com', max_length=254, verbose_name='Group Email')),
                ('direct_phone_number', models.CharField(blank=True, default='', max_length=12, verbose_name='Direct Phone Number')),
                ('cell_phone_number', models.CharField(blank=True, default='', max_length=12, verbose_name='Cell Phone Number')),
                ('home_phone_number', models.CharField(blank=True, default='', max_length=12, verbose_name='Home Phone Number')),
                ('security_level', models.CharField(choices=[('E', 'Employee'), ('M', 'Manager'), ('S', 'Supervisor')], default='E', max_length=1, verbose_name='Security Level')),
                ('manager', models.CharField(blank=True, default='manager', max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
