# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 01:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('middle_initial', models.CharField(blank=True, default='', max_length=1, verbose_name='MI')),
                ('supervisor', models.CharField(blank=True, default='supervisor', max_length=40)),
                ('division', models.CharField(choices=[('NIT', 'NIT'), ('DEF', 'DEF'), ('GHI', 'GHI'), ('JKL', 'JKL')], default='NIT', max_length=3)),
                ('office', models.CharField(choices=[('2301', '2301'), ('2302', '2302'), ('2303', '2303'), ('4999', '4999')], default='2301', max_length=4)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('job_title', models.CharField(choices=[('EO', 'Escrow Officer'), ('TO', 'Title Officer')], default='EO', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('group_email', models.EmailField(default='group@example.com', max_length=254, verbose_name='Group Email')),
                ('direct_phone_number', models.CharField(blank=True, default='', max_length=12, verbose_name='Direct Phone Number')),
                ('cell_phone_number', models.CharField(blank=True, default='', max_length=12, verbose_name='Cell Phone Number')),
                ('home_phone_number', models.CharField(blank=True, default='', max_length=12, verbose_name='Home Phone Number')),
                ('security_level', models.CharField(choices=[('S', 'Supervisor'), ('M', 'Manager'), ('E', 'Employee')], default='E', max_length=1, verbose_name='Security Level')),
                ('manager', models.CharField(blank=True, default='manager', max_length=40)),
            ],
        ),
    ]
